table dCalendar
	lineageTag: 03c6aa18-9fcc-407d-9b97-8eec09f8d743
	dataCategory: Time

	column Data
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 10cb7707-2952-4679-9788-798c79771ce7
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 4cac6803-e5a5-435a-9adc-7f6e72b06b25
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 684cd355-c7e2-4523-8937-16531e5d4d4f
		summarizeBy: none
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: 3ac7356a-0967-47ae-9cd7-9780d5286bfc
		summarizeBy: none
		sourceColumn: Nome do Mês
		sortByColumn: Mês

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: f343b8f0-66ac-4589-9652-11611484eb53
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Mês Abreviado'
		dataType: string
		lineageTag: a83e2300-1503-4eb9-a215-aab3f6278529
		summarizeBy: none
		sourceColumn: Mês Abreviado
		sortByColumn: Mês

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: d0a15492-a2ea-4a31-8db0-b48920a7f3b3
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Nome do dia'
		dataType: string
		lineageTag: 0ed37c34-89fd-49f9-9649-cda25904a27f
		summarizeBy: none
		sourceColumn: Nome do dia
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition dCalendar = m
		mode: import
		source =
				let
				    // 1. Identificar as datas mínima e máxima da tabela de fatos
				    FonteDados = #"public v_fact_order_itens", // Substitua pelo nome da sua tabela de fatos
				    DataMinima = List.Min(FonteDados[order_purchase_timestamp]), // Substitua pelo nome da sua coluna de data
				    DataMaxima = List.Max(FonteDados[order_purchase_timestamp]), // Substitua pelo nome da sua coluna de data
				
				    // 2. Ajustar para o início do primeiro ano e fim do último ano (opcional, mas recomendado)
				    DataInicio = Date.StartOfYear(DataMinima),
				    DataFim = Date.EndOfYear(DataMaxima),
				
				    // 3. Calcular o número de dias entre as datas
				    QtdeDias = Duration.Days(DataFim - DataInicio) + 1,
				
				    // 4. Gerar a lista de datas
				    ListaDatas = List.Dates(DataInicio, QtdeDias, #duration(1, 0, 0, 0)),
				
				    // 5. Converter a lista em tabela
				    Tabela = Table.FromList(ListaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				
				    // 6. Renomear a coluna e alterar o tipo para Data
				    #"Colunas Renomeadas" = Table.RenameColumns(Tabela,{{"Column1", "Data"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type date}}),
				
				    // 7. Adicionar colunas adicionais úteis (Ano, Mês, Nome do Mês, etc.)
				    #"Inserir Ano" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Inserir Mês" = Table.AddColumn(#"Inserir Ano", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Inserir Nome do Mês" = Table.AddColumn(#"Inserir Mês", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Inserted Day" = Table.AddColumn(#"Inserir Nome do Mês", "Day", each Date.Day([Data]), Int64.Type),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Inserted Day",{{"Nome do Mês", Text.Proper, type text}}),
				    #"Inserted First Characters" = Table.AddColumn(#"Capitalized Each Word", "Mês Abreviado", each Text.Start([Nome do Mês], 3), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted First Characters", "Day of Week", each Date.DayOfWeek([Data], Day.Monday), Int64.Type),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Day of Week", "Nome do dia", each if [Day of Week] = 0 then "Segunda" else if [Day of Week] = 1 then "Terça" else if [Day of Week] = 2 then "Quarta" else if [Day of Week] = 3 then "Quinta" else if [Day of Week] = 4 then "Sexta" else if [Day of Week] = 5 then "Sábado" else if [Day of Week] = 6 then "Domingo" else null, type text)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

